repos:
    - repo: https://github.com/ambv/black
      rev: stable
      hooks:
          - id: black
            language_version: python3.6
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.7.9
      hooks:
          - id: flake8
    - repo: local
      hooks:
          - id: tests
            name: run tests
            entry: py.test -svv
            language: system
            types: [python]
            always_run: true
            pass_filenames: false
            stages: [commit, push]
